parameters:
    blog_file_edited: true
    blog_name: 'Konniblog test'
    blog_description: 'this is a test'
    blog_email: contact@fdweb.fr
    blog_allowusers: true
    blog_validateusers: true
    blog_email_onregistration: true
    blog_allowcomments: true
    blog_allowanonymous: true
    blog_validatecomments: true
    blog_email_oncomment: true
